apiVersion: v2
name: drone-kubernetes-secrets
description: A Kubernetes Secrets extension for Drone
type: application
version: 0.1.1
appVersion: 1.0.0
kubeVersion: "^1.13.0-0"
home: https://github.com/drone/drone-kubernetes-secrets
icon: https://drone.io/apple-touch-icon.png
keywords:
  - continuous-delivery
  - continuous-deployment
  - continuous-integration
  - docker
  - drone
  - drone.io
  - go
sources:
  - https://github.com/drone/drone-kubernetes-secrets
  - https://github.com/drone/helm
maintainers:
  - name: Drone
    email: hello@drone.io
