apiVersion: v2
name: drone-kubernetes-secrets
description: A Kubernetes Secrets extension for Drone
type: application
version: 0.2.0
appVersion: 1.2.0
kubeVersion: "^1.13.0-0"
home: https://docs.drone.io/runner/extensions/kube/
icon: https://docs.drone.io/logo.svg
keywords:
  - continuous-delivery
  - continuous-deployment
  - continuous-integration
  - docker
  - drone
  - drone.io
  - go
sources:
  - https://github.com/drone/drone-kubernetes-secrets
  - https://github.com/drone/charts
maintainers:
  - name: Drone
    email: hello@drone.io
